version: '3.4'

services:
  web_client:
    build: ./Webapp
    depends_on:
      - mobile_client
      - server
    volumes:
      - ./Webapp:/usr/src/app:z
      - /usr/src/app/node_modules
    ports:
      - 8081:8081
  server:
    image: ${DOCKER_REGISTRY}server
    build: 
      context: .
      dockerfile: Area_api/Area.Api/Dockerfile
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
      - ASPNETCORE_URLS=http://+:80
      - ASPNETCORE_HTTP_PORT=8080
    ports:
        - "8080:80"
    volumes:
      - ${APPDATA}/ASP.NET/Https:/root/.aspnet/https:ro
      - ${APPDATA}/Microsoft/UserSecrets:/root/.microsoft/usersecrets:ro
  mobile_client:
    build: ./Mobile
    volumes:
    - .:/application
    command: bash -c "cd Mobile/ && npm install && cd android/ && ./gradlew build"